stages:
   - documentation
   - quality
   - build
   - active_tests

variables:
  GIT_STRATEGY: clone
  TIMEOUT: 10m

docs:
   stage: documentation
   script:
      - make docs
   artifacts:
      paths:
         - docs/code/src

versionInfo:
   stage: documentation
   script:
      - make version

styleCheck:
   stage: quality
   script:
      - make style

staticAnalysis:
   stage: quality
   script:
      - make static

build:
   stage: build
   script:
      - make birdSim

memoryLeaks:
   stage: active_tests
   script:
      - make memcheck
