stages:
   - documentation
   - quality
   - build
   - unit_test
   - test_quality

docs:
   stage: documentation
   script:
      - make docs
   artifacts:
      paths:
         - docs

style:
   stage: quality
   script:
      - make style

staticAnalysis:
   stage: quality
   script:
      - make static

buildTests:
   stage: build
   script:
      - make test_project
   artifacts:
      paths:
         - test_project

unitTests:
   stage: unit_test
   script:
      - test_project

memoryLeaks:
   stage: test_quality
   script:
      - make memcheck

coverage:
   stage: test_quality
   script:
      - make coverage
   artifacts:
     paths:
        - coverage
